Main algo heavily simplified.

diff --git a/src/bash-magic-enviro b/src/bash-magic-enviro
--- a/src/bash-magic-enviro
+++ b/src/bash-magic-enviro
@@ -2,14 +2,14 @@
 #
 # This file is meant to be sourced, not run
 BME_SRC_DIR='/home/jmnav/REPOS/bash-magic-enviro'
-BME_VERSION='v1.2.3'
+BME_VERSION='v1.3.0'
 # BME_SRC_DIR=<% BME_SRC_DIR %>
 # BME_VERSION=<% BME_VERSION %>
 BME_PROJECT_FILE='.bme_project'
 BME_FILE='.bme_env'
 BME_HIDDEN_DIR='.bme.d'
 BME_CONFIG_DIR="${HOME}/${BME_HIDDEN_DIR}"
-BME_WHITELISTED_FILE="${BME_CONFIG_DIR}/whitelistedpaths.txt"
+BME_WHITELISTED_FILE="${BME_CONFIG_DIR}/whitelistedpaths"
 
 # Style table
 export C_BOLD='\033[1m'         # Bold text
@@ -23,7 +23,7 @@ declare -i BOOL=(0 1)
 true=${BOOL[0]}
 false=${BOOL[1]}
 
-DEBUG=$true
+# DEBUG=$true
 
 # See at the end of this script one-off "pseudo-main" code
 
@@ -31,71 +31,44 @@ DEBUG=$true
 # FUNCTIONS
 #--
 # Main BME loader (it runs each time we change directory as per PROMPT_COMMAND)
-# it first looks for a "project file" (.bme_project), then for a "config file" (.bme_env)
 bme_eval_dir() {
 	if [ "$PWD" != "$MYOLDPWD" ]; then
 		MYOLDPWD="$PWD"
-		if [ -e ${BME_PROJECT_FILE} ]; then
-			if [[ -n ${BME_PROJECT_NAME+x} ]]; then
-				local new_project=$(source "${BME_PROJECT_FILE}" && echo "${BME_PROJECT_NAME}")
-				__bme_debug && echo "A new ${BME_PROJECT_NAME} found: CURRENT '${BME_PROJECT_NAME}' vs NEW '${new_project}'"
-				if [ "${new_project}" != "${BME_PROJECT_NAME}" ]; then
-					__bme_clean_project || return $?
-				fi
-			fi
-			if __bme_whitelist "$PWD"; then
-				__bme_process_known_projects "$PWD" || return $?
-				__bme_load_project "$PWD" || return $?
+	# Find "nearest" project file climbing "upwards" the filesystem hierarchy
+		local nearest_project_dir="$PWD"
+		local project_found=false
+		while [ "${nearest_project_dir}" ]; do
+			__bme_debug && echo "${FUNCNAME[0]}: Looking for '${BME_PROJECT_FILE}' at '${nearest_project_dir}'."
+			if [ -e "${nearest_project_dir}/${BME_PROJECT_FILE}" ]; then
+			# Found "nearest" project file
+				__bme_debug && echo "${FUNCNAME[0]}: Found project file at '${nearest_project_dir}'."
+				__bme_load_project "${nearest_project_dir}" || return $?
+				project_found=true
+				break
 			else
-				bme_log "${C_BOLD}'${BME_PROJECT_FILE}'${C_NC} file found, but load was rejected." fail
+			# go one directory upwards and retry
+				nearest_project_dir=$(dirname "${nearest_project_dir}")
+				nearest_project_dir=${nearest_project_dir%/}  # in case returned dir ends in slash, delete it.
 			fi
+		done
+		if ! $project_found && [[ -n ${BME_PROJECT_NAME+x} ]]; then
+			# Still within a project context, but no project to load found in filesystem hierarchy.
+			__bme_debug && echo "Project loop finished and no project found"
+			__bme_clean_project
 		fi
-	# this conditional matches when we go "above" the project's root directory
-		if [ "${PWD##$BME_PROJECT_DIR}" == "$PWD" ] && [[ -n ${BME_PROJECT_DIR+x} ]]; then
-			__bme_clean_project || return $?
-		# now, check if current dir belongs to an already known project
-			local project
-			for project in "${!BME_LOADED_PROJECTS[@]}"; do
-				local project_root_dir="${BME_LOADED_PROJECTS[${project}]}"
-				if ! [ "${PWD##$project_root_dir}" == "$PWD" ]; then
-				# Within an already known project
-					__bme_debug && echo "WITHIN PROJECT AT '${project_root_dir}'"
-					if __bme_whitelist "${project_root_dir}"; then
-						__bme_load_project "${project_root_dir}"
-					fi
-					break
-				fi
-			done
-			unset project
-		fi
-	# One way or the other, ${BME_PROJECT_FILE} is already processed when reaching this point.
-	# time now for the ${BME_FILE}
+		
+	# Reaching this point, a project should already be loaded, if any available.
+	# Time to process 'bme_env' files, if any
 		if [ -e ${BME_FILE} ]; then
-			__bme_debug && echo "${BME_FILE} FOUND"
-			if __bme_whitelist "$PWD"; then
-				__bme_debug && echo "${BME_FILE} WHITELISTED"
-			else
-				bme_log "${C_BOLD}'${BME_FILE}'${C_NC} file found, but load was rejected (see ${C_BOLD}'${BME_WHITELISTED_FILE}'${C_NC} contents)." warning
-			fi
+			__bme_debug && echo "${BME_FILE} found at ${PWD}"
 			if [[ -n ${BME_PROJECT_NAME+x} ]]; then
-				source ${BME_FILE}
+			# Already within a validated project context.
+				source "${BME_FILE}"
 			else
-			# Trying to find the "deepest" parent
-				local project_dir=""
-				for dir in "${!BME_WHITELISTED_PATHS[@]}"; do
-					# remember how this returns false if we are "within" a directory and true if not
-					if ! [ "${PWD##$dir}" == "${PWD}" ]; then
-						__bme_debug && echo "parent match for enviro dir"
-						((${#dir} > ${#project_dir})) && project_dir="${dir}"
-					fi
-				done
-				if [ -n "${project_dir}" ]; then
-					__bme_load_project "${project_dir}" || return $?
-				else
-					local log_msg="${C_BOLD}'${BME_FILE}'${C_NC} file found, but no project root found.\n"
-					log_msg+="\tReview your directory hierarchy leading to ${C_BOLD}'${PWD}'${C_NC}."
-					bme_log "${log_msg}" error
-				fi
+				local log_msg="${C_BOLD}'${BME_FILE}'${C_NC} file found, but no project root found.\n"
+				log_msg+="\tReview your directory hierarchy leading to ${C_BOLD}'${PWD}'${C_NC}."
+				bme_log "${log_msg}" error
+				return -1
 			fi
 		fi
 	fi
@@ -180,42 +153,10 @@ local full_message=''
 export -f bme_log
 
 
-# Manages array of known projects
-# 1st param: 'project_dir': the directory to look for a project file
-__bme_process_known_projects() {
-local project_dir="${1}"
-
-# Just once, on a new "BME session"
-	if ! [ -v BME_LOADED_PROJECTS[@] ]; then
-		__bme_debug && echo "Creating BME_LOADED_PROJECTS"
-		declare -Ag BME_LOADED_PROJECTS
-	fi
-# Loads the new project file in a subshell to check if it's a new project
-	local new_project=$(source "${project_dir}/${BME_PROJECT_FILE}" && echo "${BME_PROJECT_NAME}")
-# 	if [[ -z "${new_project}" ]]; then
-# 		bme_log "You didn't set ${C_BOLD}'BME_PROJECT_NAME=[your_project_name]'${C_NC} in your ${C_BOLD}'${BME_PROJECT_FILE}'${C_NC} file." fatal
-# 		return -1
-# 	fi
-	
-	if ! [ -v BME_LOADED_PROJECTS["${new_project}"] ]; then
-		__bme_debug && echo "${new_project} not listed."
-# 		__bme_check_project_name "${new_project}" || return $?
-		BME_LOADED_PROJECTS["${new_project}"]+="${PWD}"
-		__bme_debug && echo "new root project: ${BME_LOADED_PROJECTS[${new_project}]}"
-	else
-		__bme_debug && echo "root project already known: ${BME_LOADED_PROJECTS[${new_project}]}"
-	fi
-	__bme_debug && echo "Currently known projects:" `typeset -p BME_LOADED_PROJECTS` "."
-# Makes sure this function returns something
-	return 0
-}
-
-
 # Loads a project's configuration
 # 1st param: 'project_dir': the directory to look for a project file
 __bme_load_project() {
 local project_dir="${1}"
-
 # A bit of debug: I need to know the place I'm stored, so I can find other includes, relative to me
 # 	echo "See what follows: $0"
 # 	echo "See what follows: $_"
@@ -230,20 +171,46 @@ local project_dir="${1}"
 		return -1
 	fi
 	
-	# if $BME_PROJECT_NAME is defined, we are already within a "BME session"
-	if [[ -n ${BME_PROJECT_NAME+x} ]]; then
-		__bme_debug && echo "ALREADY WITHIN A PROJECT ENVIRONMENT"
-		return 0
-	fi
-	
-#  Let's make sure we are invoked only once
-	if [[ -n ${PROJECT_DIR+x} ]]; then
-		bme_log "Function ${C_BOLD}'${FUNCNAME[0]}()'${C_NC} can only be called once per project session!" error
+# Check if really there's a project file where requested
+	if [ ! -r "${project_dir}/${BME_PROJECT_FILE}" ]; then
+		bme_log "${FUNCNAME[0]}: No ${C_BOLD}'${BME_PROJECT_FILE}'${C_NC} found at ${C_BOLD}''${C_NC}." fatal
 		return -1
 	fi
 	
-# "Real" processing starts here
-	source "${project_dir}/${BME_PROJECT_FILE}"
+# if $BME_PROJECT_NAME is defined, we are already within a "BME session"
+	if [[ -n ${BME_PROJECT_NAME+x} ]]; then
+		__bme_debug && echo "${FUNCNAME[0]}: ALREADY WITHIN A PROJECT ENVIRONMENT"
+		local new_project=$(source "${project_dir}/${BME_PROJECT_FILE}" && echo "${BME_PROJECT_NAME}")
+		if [[ -z "${new_project}" ]]; then
+			bme_log "You didn't set ${C_BOLD}'BME_PROJECT_NAME=[your_project_name]'${C_NC} in your ${C_BOLD}'${BME_PROJECT_FILE}'${C_NC} file." error
+			return -1
+		fi
+		
+		if [ "${new_project}" != "${BME_PROJECT_NAME}" ]; then
+		# New project: clean old one
+			__bme_clean_project || return $?
+		elif [ "${project_dir}" != "${BME_PROJECT_DIR}" ]; then
+		# Weird: it seems we found the same project name at two different locations
+			local log_msg="${C_BOLD}'${BME_PROJECT_NAME}'${C_NC} found at two different locations:\n"
+			log_msg+="\t${C_BOLD}'${BME_PROJECT_DIR}'${C_NC} vs ${C_BOLD}'${project_dir}'${C_NC}.\n"
+			log_msg+="Cleaning anyway."
+			bme_log "${log_msg}" warning
+			__bme_clean_project || return $?
+		else
+		# Still within same project; do nothing
+			return 0
+		fi
+	fi
+	
+# If we reached here, it's time to load a new project
+# Check project's whitelisting status
+	if ! __bme_whitelist "${project_dir}"; then
+		bme_log "${C_BOLD}'${BME_PROJECT_FILE}'${C_NC} file found at ${C_BOLD}'${project_dir}'${C_NC}, but load was rejected." fail
+		return -1
+	fi
+	
+# Load already validated project
+	source "${project_dir}/${BME_PROJECT_FILE}" || return $?
 	bme_log "project ${C_BOLD}'${BME_PROJECT_NAME}'${C_NC} environment..." loading
 	
 	export BME_PROJECT_DIR="${project_dir}"
@@ -305,6 +272,7 @@ local allowed_callers=('__bme_load_project' 'bme_eval_dir')
 		return -1
 	fi
 	
+	bme_log "Cleaning ${C_BOLD}'${BME_PROJECT_NAME}'${C_NC}..." cleaning
 	local project_name="${BME_PROJECT_NAME}"
 	
 # Custom clean (if any)
@@ -345,11 +313,12 @@ local allowed_callers=('__bme_load_project' 'bme_eval_dir')
 
 
 # Whitelists projects
+# 1st param: the directory to check for whitelisting
 __bme_whitelist() {
 local test_path="${1}"
 
 # "pseudo private" function protection
-local allowed_callers=('bme_eval_dir' '__bme_whitelist')
+local allowed_callers=('__bme_load_project')
 	if [[ ! " ${allowed_callers[*]} " =~ " ${FUNCNAME[1]} " ]]; then
 		local log_msg="Function ${C_BOLD}'${FUNCNAME[0]}()'${C_NC} is ${C_BOLD}private${C_NC}.  You shouldn't invoke it!\n"
 		log_msg+="\tUnexpectedly called from ${C_BOLD}'${FUNCNAME[1]}'${C_NC}."
@@ -357,50 +326,31 @@ local allowed_callers=('bme_eval_dir' '__bme_whitelist')
 		return -1
 	fi
 	
-# Checks whitelisting status of known directories
-	__bme_debug && echo -n "Checking whitelist status of "
-	if [ -e "${test_path}/${BME_PROJECT_FILE}" ]; then
-		local match='exact'
-		__bme_debug && echo -n "project directory "
-	elif [ -e "${test_path}/${BME_FILE}" ]; then
-		local match='parent'
-		__bme_debug && echo -n "enviro directory "
-	fi
-	__bme_debug && echo "'${test_path}'"
-	
-	local dir
-	local candidate_dir=""
-	for dir in "${!BME_WHITELISTED_PATHS[@]}"; do
-		__bme_debug && echo -e "...against directory '${dir}'"
-		if [ $match == 'exact' ]; then
-			if [ "$dir" == "${test_path}" ]; then
-				# returns the true/false allowance value associated with this directory
-				__bme_debug && echo "exact match for project dir"
-				return ${!BME_WHITELISTED_PATHS[$dir]}
-			fi
-		elif [ $match == 'parent' ]; then
-		# in case of parent matching, there can be more than one "parent" above current dir (subprojects)
-		# First, we try to find the "deepest" parent
-			# remember how this returns false if we are "within" a directory and true if not
-			if ! [ "${test_path##$dir}" == "${test_path}" ]; then
-				__bme_debug && echo "parent match for enviro dir"
-				((${#dir} > ${#candidate_dir})) && candidate_dir="${dir}"
-			fi
-		fi
-	done
-	# Here, either already exited this function or found the deepest project "candidate" for a .bme_env file
-	if [ -n "${candidate_dir}" ]; then
-		__bme_debug && echo "Testing candidate dir '${candidate_dir}'"
-		# ...even then, there can be an still unknown project file between current dir and deepest candidate
-		# recursive search and return if an answer is found
-		while [ "${test_path##$candidate_dir}" ]; do
-			test_path=$(dirname "${test_path}")
-			__bme_whitelist "${test_path}"
-			return $?
-		done
+# Safe check: is this really a "project directory"?
+	if ! [ -f "${test_path}/${BME_PROJECT_FILE}" ]; then
+		local log_msg="${C_BOLD}'${FUNCNAME[0]}()'${C_NC} called from ${C_BOLD}'${FUNCNAME[1]}()'${C_NC}:\n"
+		log_msg+="\twhitelisting status for ${C_BOLD}'${test_path}'${C_NC} requested, but no ${C_BOLD}${BME_PROJECT_FILE}${C_NC} file found at that place."
+		bme_log "${log_msg}" fatal
+		return -1
 	fi
 	
-# If we reached here, it's a new project
+# Loops to find if it's an already known project directory
+	if [[ -v BME_WHITELISTED_PATHS["${test_path}"] ]]; then
+		__bme_debug && echo "${FUNCNAME[0]} called from ${FUNCNAME[1]}: exact match found:"
+		__bme_debug && echo -e "\t'${test_path}' whitelist status is '${BME_WHITELISTED_PATHS[$test_path]}'."
+		return ${!BME_WHITELISTED_PATHS[$test_path]}
+	fi
+	
+# 	for dir in "${!BME_WHITELISTED_PATHS[@]}"; do
+# 		if [ "$dir" == "${test_path}" ]; then
+# 		# returns the true/false allowance value associated with this directory
+# 			__bme_debug && echo "${FUNCNAME[0]} called from ${FUNCNAME[1]}: exact match for project dir."
+# 			__bme_debug && echo -e "\t'${test_path}' belongs to '${dir}'."
+# 			return ${!BME_WHITELISTED_PATHS[$dir]}
+# 		fi
+# 	done
+	
+# If we reached here, it's a new project directory
 	bme_log "${C_BOLD}'${BME_PROJECT_FILE}'${C_NC} file found at ${C_BOLD}'${test_path}'${C_NC}." info
 	# First, check if its name is valid
 	local new_project=$(source "${test_path}/${BME_PROJECT_FILE}" && echo "${BME_PROJECT_NAME}")
@@ -408,10 +358,10 @@ local allowed_callers=('bme_eval_dir' '__bme_whitelist')
 		bme_log "You didn't set ${C_BOLD}'BME_PROJECT_NAME=[your_project_name]'${C_NC} in your ${C_BOLD}'${BME_PROJECT_FILE}'${C_NC} file." fatal
 		return -1
 	fi
-	__bme_debug && echo "New project name is '${new_project}'"
+	__bme_debug && echo "${FUNCNAME[0]}: New project name is '${new_project}'"
 	__bme_check_project_name "${new_project}" || return $?
 	
-	echo -en 'Do you want to whitelist this directory? [y/N]: '
+	echo -en '\tDo you want to whitelist this directory? [y/N]: '
 	while true; do
 		read -r REPLY
 		REPLY="${REPLY:-N}"  # reply defaults to 'N'
@@ -429,7 +379,7 @@ local allowed_callers=('bme_eval_dir' '__bme_whitelist')
 			;;
 			*)
 				# these control codes "overwrite" de console line
-				echo -en "\r\033[1A\033[0K${C_RED}Only 'y' or 'n' allowed!${C_NC} Do you want to whitelist this directory? [y/N]: "
+				echo -en "\r\033[1A\033[0K${C_RED}\tOnly 'y' or 'n' allowed!${C_NC} Do you want to whitelist this directory? [y/N]: "
 			;;
 		esac
 	done
@@ -452,7 +402,7 @@ __bme_check_project_name() {
 local project_name=$1
 local bad_name=false
 
-local allowed_callers=('__bme_process_known_projects' '__bme_whitelist')
+local allowed_callers=('__bme_whitelist')
 	if [[ ! " ${allowed_callers[*]} " =~ " ${FUNCNAME[1]} " ]]; then
 		local log_msg="Function ${C_BOLD}'${FUNCNAME[0]}()'${C_NC} is ${C_BOLD}private${C_NC}.  You shouldn't invoke it!\n"
 		log_msg+="\tUnexpectedly called from ${C_BOLD}'${FUNCNAME[1]}'${C_NC}."
@@ -493,16 +443,6 @@ local allowed_callers=('__bme_process_known_projects' '__bme_whitelist')
 }
 
 
-# Checks if current path belongs to a known project
-__bme_check_project_path() {
-	local project
-	for project in "${!BME_LOADED_PROJECTS[@]}"; do
-		local project_root_dir="${BME_LOADED_PROJECTS[${project}]}"
-		if ! [ "${PWD##$project_root_dir}" == "$PWD" ]; then
-			echo "${project_root_dir}"
-		fi
-	done
-}
 
 #--
 # MAIN
@@ -513,7 +453,8 @@ if ! [ -d "${BME_CONFIG_DIR}" ]; then
 	bme_log "${C_BOLD}'${BME_CONFIG_DIR}'${C_NC} directory doesn't exist.  Creating it" info
 	mkdir -p "${BME_CONFIG_DIR}" || return $?
 fi
-if ! [ -r "${BME_WHITELISTED_FILE}" ]; then
+if ! [ -e "${BME_WHITELISTED_FILE}" ]; then
+# Creates an "empty" white list if it didn't yet exist
 	echo -e "declare -gA BME_WHITELISTED_PATHS=(\n)" > "${BME_WHITELISTED_FILE}"
 fi
 source "${BME_WHITELISTED_FILE}"
